### ISSUE TITLE
[number input] Buggy placeholder display

### ISSUE THREAD

**Issue by oliviertassinari** [mui/base-ui#226]
### Steps to reproduce

The way the `value` is controlled looks broken:

https://github.com/mui/base-ui/assets/3165635/20718d78-bcdb-417d-8000-e733cdebf193

https://codesandbox.io/p/sandbox/ecstatic-franklin-gsfqy3?file=%2Fpackage.json%3A5%2C34

### Context

I saw this in #163

### Your environment

`"@mui/base": "5.0.0-beta.40",`

**Search keywords**: placeholder flash

**Comment by danilo-leal** [comment]
Does having these issues open about the outdated Number Field demos/implementation make sense? I think all of these should be resolved with the new one @atomiks and @colmtuite are working on.

**Comment by colmtuite** [comment]
Yep the new NumberField should be merged end of next week, and all issues should be resolved. I've tagged open issues on each issue for new components as sub tasks, just so the assigned dev can reference older issues and make sure they're resolved in new components.

So +1 we should avoid opening issues on current components because they will all be bulldozed pretty soon.

**Comment by oliviertassinari** [comment]
> I think all of these should be resolved with the new one

@danilo-leal I guess it depends on how much we build on top of the previous component. It don't know where the root cause is. We might inherit this bug from a lower level primitive.

It's great to batch the work as well, but multiple PRs can be better sometimes, makes it easier to review, check what has test and what hasn't.

I don't have more issues to report on the number input / number field, and will hold until the focused move elsewhere 😁

**Comment by michaldudak** [comment]
The placeholder seems to be working well in the new Number Field: https://master--base-ui.netlify.app/base-ui/react-number-field/
