### ISSUE TITLE
[Textarea Autosize] Height instability

### ISSUE THREAD

**Issue by jciaffi** [mui/base-ui#325]
### Steps to reproduce

Link to live example: https://mui.com/base-ui/react-textarea-autosize/#introduction
Steps: Resize the textarea (on the above url).

### Current behavior

When I try to resize the textarea (on the above url), the height is flickering. 

### Expected behavior

Smooth resizing.

### Your environment

The same thing happens on chrome, edge, firefox (windows and mac).

**Search keywords**: Textarea Autosize

**Search keywords**:

**Comment by oliviertassinari** [comment]
cc @ZeeshanTamboli

**Comment by ZeeshanTamboli** [comment]
@jciaffi This component is getting deprecated in Base UI in the future (check: https://github.com/mui/base-ui/issues/168#issuecomment-2013935503 and https://github.com/mui/base-ui/pull/189#issuecomment-2013924919). However, for existing apps using this component and those utilizing the Material UI `TextField` with the `multiline` prop, I've implemented a fix in https://github.com/mui/material-ui/pull/41638. We're currently figuring out how to include a test for this. I'll close this issue in this repository since similar issues (#168 and mui/base-ui#160) have also been closed due to the impending deprecation in Base UI.

_Edit:_ Finally found a way to add a test for it in https://github.com/mui/material-ui/pull/41638. So the fix should be available soon.

**Comment by oliviertassinari** [comment]
Even if deprecated, it will likely take two years to remove it, the time it will take for browser support to propagate https://github.com/mui/material-ui/issues/43720.

So I'm reopening, there are no real alternatives in production today, and it's still a regression.

**Comment by oliviertassinari** [comment]
Duplicate of mui/base-ui#168
