### ISSUE TITLE
[Modal + Select] Using keyboard Esc while Modal's Select is open should not close the Modal

### ISSUE THREAD

**Issue by rh-meowsa** [mui/base-ui#327]
### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/fervent-wiles-4htkjx?file=%2Fsrc%2FDemo.tsx%3A13%2C57
Steps:
1. Create a modal and add a Select field inside it
2. Open modal
3. Open the Select dropdown
4. Press Esc on the keyboard

### Current behavior

Exits the Modal

### Expected behavior

Exits only the Select (just like mui-material)

### Context

Creating a form inside a modal for user to fill out and submit.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

  System:
    OS: macOS 14.4.1
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    pnpm: 8.6.11 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 123.0.6312.124
    Edge: Not Found
    Safari: 17.4.1
  npmPackages:
    @mui/base: 5.0.0-beta.37 => 5.0.0-beta.37
    @types/react: 18.2.42 => 18.2.42
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0

  **using Chrome 123.0.6312.124**
</details>

**Search keywords**: modal, select, escape, keyboard

**Search keywords**:

**Comment by michaldudak** [comment]
Your reproduction doesn't show the Modal. I can see what the issue is about, but could you please correct it for completeness?

We are currently redesigning Base UI components (with a different customization API), and we should tackle the Select around June (see https://github.com/orgs/mui/projects/1/views/13). We'll work on fixing this then.
