### ISSUE TITLE
[Dialog] In Safari, focus isn't returned to the trigger when dialog is closed

### ISSUE THREAD

**Issue by vladmoroz** [mui/base-ui#618]
### Steps to reproduce

Link to live example: 
https://master--base-ui.netlify.app/components/react-dialog/

### Current behavior

Focus is returned to the start of the document, apparently

### Expected behavior

Focus is returned to the trigger

### Your environment

Safari 17.6

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: safari, focus, return, trigger, close, dialog, modal

**Comment by atomiks** [comment]
@michaldudak this problem is caused by Safari not focusing buttons on mousedown, so the previously focused element isn't the trigger. 

When using `useClick` from Floating UI, this problem is solved, but custom event handlers won't work.

Possible solutions:

- Swap to the `useClick` hook
- Add the custom click mouse event to `context.dataRef.current.openEvent` (that's what the focus manager checks for)
- Return focus manually for Safari

I don't think switching to `useButton` and rendering a `<div>` (which might take focus instead) will be reliable since they compose a native `<button>` tag in theory.

**Comment by onehanddev** [comment]
Hi @vladmoroz @michaldudak 
I would love to pick this up, please let me know if its ready for dev. Thanks !

**Comment by michaldudak** [comment]
This is one of the issues that should be resolved once we change the implementation to handle the trigger with Floating UI (similarly to https://github.com/mui/base-ui/issues/619)
