### ISSUE TITLE
Support non main document: iframe, popup, etc

### ISSUE THREAD

**Issue by oliviertassinari** [mui/base-ui#629]
### Steps to reproduce

There are a number of components that are broken when used in non main window context, meaning in iframe, popup, shadow dom. A few quick examples:

- Dialog

https://github.com/mui/base-ui/blob/1ab27b0510e0ba19157597f17642022a6208ae09/packages/mui-base/src/utils/useScrollLock.ts#L43

- NumberInput

https://github.com/mui/base-ui/blob/1ab27b0510e0ba19157597f17642022a6208ae09/packages/mui-base/src/NumberField/ScrubAreaCursor/NumberFieldScrubAreaCursor.tsx#L46

- Slider

https://github.com/mui/base-ui/blob/1ab27b0510e0ba19157597f17642022a6208ae09/packages/mui-base/src/Slider/Root/useSliderRoot.ts#L379

### Context

A few related issues: https://github.com/mui/material-ui/pull/18701, https://github.com/mui/material-ui/pull/10328.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: -

**Comment by atomiks** [comment]
For the Slider case, it seems valid that it should use `ownerDocument` instead of the main document.

For NumberField, I think the cursor should always be in the top-level document (when it can, in the same origin). This way it always appears even when the cursor has left the iframe while scrubbing, as it acts like an OS-level element.

For useScrollLock, I'm not sure on this one. It seems that it could be favorable to lock the main/parent window even if the locked element is inside an iframe. This doesn't work for embeds on different origins of course.
