### ISSUE TITLE
[Select] Select menu can't be closed by clicking away

### ISSUE THREAD

**Issue by homerchen19** [mui/base-ui#8]
### Steps to reproduce

Link to live example: https://mui.com/base-ui/react-select/#introduction

Steps:
1. Add `value=""` to the `<Select>` component

![Screenshot 2024-02-19 at 13 36 06](https://github.com/mui/material-ui/assets/12113222/33c68774-2406-4155-8201-f21acf08d20a)

### Current behavior

- The Select menu can't be closed by clicking away if its `value` prop doesn't match any option's value
- Selecting an option can close the menu though

### Expected behavior

- The Select menu can be closed by clicking away even if its `value` prop doesn't match any option's value

### Your environment

<details>
"@mui/base": "5.0.0-beta.36"
</details>

**Search keywords**: Select

**Comment by mj12albert** [comment]
@homerchen19 Thanks for reporting this - I thought it may be because you set both `defaultValue` and `value` in your screenshot, but I can reproduce it with an out of range `value` (no `defaultValue`)

Just for comparison: clickaway works correctly with an out of range `value` in Material UI's Select ([demo](https://stackblitz.com/edit/mcve-react-material-ui-yscga7?file=src%2FApp.tsx))
```
<Select value="abc" label="Age">
  <MenuItem value={10}>Ten</MenuItem>
  <MenuItem value={20}>Twenty</MenuItem>
</Select>
```

**Comment by homerchen19** [comment]
JFYI, I noticed this bug after installing version `"5.0.0-beta.29"` which contains this [PR](https://github.com/mui/material-ui/pull/39675)
